Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
        vb.name = "micro_prod_01"
        vb.memory = 1024
        vb.cpus = 1
    end
    #Instância
    config.vm.box = "hashicorp/bionic64"
    # Liberação de portas
    config.vm.network "forwarded_port" , guest: 80 , host: 8090
    #Liberação de rede
    config.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9462"
    # Utilizando shell script
    config.vm.provision "shell", path: "script.sh"
    # Pasta sincronizada so site que está em prod.
    config.vm.synced_folder "site/" , "/var/www/html"
  end